import { ITypographyStyles } from '../FigmaDesignTokensGenerator';
import { prettifyContent } from './prettify-content';

export type IFormatType = 'module' | 'object';

const autogeneratedText = `/**
 * This file is autogenerated by "figma-design-tokens"!
 * Last updated: ${new Date().toLocaleString('da-DK')}
 *  If you edit this file, it will be overwritten, next time you run the command.
 */\n
`;

const formatName = (name: string): string => {
  const splitName = name
    .toLowerCase()
    .split('/')
    .map((item, index) => {
      if (index !== 0) return item.charAt(0).toUpperCase() + item.slice(1);

      return item.trim();
    });

  return splitName.join('').replace(/[-/() ]/g, '');
};

export const formatTypographyTokensAsTailwind = async (
  typographyTokens: ITypographyStyles[],
  type: IFormatType = 'module'
) => {
  let content = autogeneratedText;
  let contentWrapperTailwind = ``;

  for (const token of typographyTokens) {
    let css = '';
    if (token.cssStyle && typeof token.cssStyle === 'object') {
      css = `[
    '${token.cssStyle?.fontSize}',
    {
      lineHeight: '${token.cssStyle?.lineHeight}',
      letterSpacing: '${token.cssStyle?.letterSpacing}',
      fontWeight: ${token.cssStyle?.fontWeight},
    },
  ]`;

      contentWrapperTailwind += `  // FontFamily is: "${
        token.cssStyle.fontFamily
      }
  // https://www.figma.com/file/KvnKtVv6syZZUb5XJrUkWl/NUI?type=design&node-id=${
    token.nodeId
  }"
  ${formatName(token.name)}: ${css},\n`;
    }
  }

  if (!contentWrapperTailwind.length) {
    throw new Error('No tokens found');
  }

  if (type === 'module') {
    content += `module.exports = { ${contentWrapperTailwind}};`;
  } else {
    content += `export const typographyTokens = {
      ${contentWrapperTailwind}
      } satisfies Record<
        string,
        [
          fontSize: string,
          configuration: Partial<{
            lineHeight: string;
            letterSpacing: string;
            fontWeight: string | number;
          }>,
        ]
      >;
    `;
  }

  return prettifyContent(content);
};
