import * as prettier from 'prettier';

export const autogeneratedText = `/**
 * This file is autogenerated by "figma-design-tokens"!
 * Last updated: ${new Date().toLocaleString('da-DK')}
 * If you edit this file, it will be overwritten, next time you run the command.
 */\n
`;

export async function prettifyContent(content: string) {
  const formattedContent = await prettier.format(content, {
    parser: 'typescript',
    singleQuote: true,
    semi: true,
    useTabs: false,
    tabWidth: 2,
    trailingComma: 'es5',
    bracketSpacing: true,
    arrowParens: 'always',
    embeddedLanguageFormatting: 'auto',
    proseWrap: 'preserve',
    printWidth: 80,
  });

  return formattedContent;
}
