import {
  Color,
  IStyleMetadata,
  IVariable,
  IVariableCollection,
  VariableCollectionId,
  VariableId,
  isColorValue,
  isVariableAlias,
} from './figmaAPI/apiTypes';
import {
  fetchFigmaFileNodes,
  fetchFigmaFileNodesBatched,
  fetchFigmaFileStyles,
  fetchFigmaStyles,
  fetchFigmaVariables,
} from './figmaAPI/figmaAPI';
import { FigmaNode, TypeStyle } from './figmaAPI/types';
import { convertRgbaToHex } from './utils/convert-color';
import { createTokenFile } from './utils/create-file';
import { findTypographyTokens } from './utils/findToken';
import { formatTypographyTokensAsTailwind } from './utils/formatTypographyTokensAsTailwind';
import { logMessage } from './utils/logMessage';
import { autogeneratedText, prettifyContent } from './utils/prettify-content';
import { IConfig, IConfigV1, INode } from './types';
import chalk from 'chalk';

export interface ICssStyle {
  fontFamily?: string;
  fontSize?: string;
  fontWeight?: number;
  lineHeight?: string;
  textTransform?: string;
  letterSpacing?: string;
}

export interface ITypographyStyles {
  name: string;
  cssStyle?: ICssStyle | string;
  nodeId?: string;
  description?: string;
}

export class FigmaDesignTokensGenerator<T extends IConfig = IConfig> {
  private config: T;
  private nodes: INode[] = [];
  private styles: IStyleMetadata[];
  private variables: Record<VariableId, IVariable>;
  private variableCollections: Record<
    VariableCollectionId,
    IVariableCollection
  >;
  private isMissingCollectionsOrNodes = false;
  private valid = false;
  public appName: string = '';

  /**
   * Generates design token files from a Figma team library
   *
   * Call the generate method to start generating design tokens.
   *
   * @param config - Configuration object
   */
  constructor(config: T) {
    // replace dashes with colons in nodeIds to match figma api
    if (config.version === 1 && config.nodes?.length) {
      this.nodes = config.nodes?.map((node) => ({
        ...node,
        nodeId: node.nodeId.replace(/-/g, ':'),
      }));
    }

    this.config = config;
    this.appName = config.appName;
    this.styles = [];
    this.variables = {};
    this.variableCollections = {};

    if (!this.appName) {
      logMessage(
        `App name is required for config:\n${JSON.stringify(this.config, null, 2)}`,
        'error'
      );
      process.exit(1);
    }

    if (this.config.figmaApiToken) {
      this.logMessage(
        'Using Figma API token from config file, instead of .env variable'
      );
      process.env.FIGMA_API_TOKEN = config.figmaApiToken;
    }

    if (!process.env.FIGMA_API_TOKEN) {
      this.logMessage(
        'Add your FIGMA_API_TOKEN to an .env file, located in the root of the project',
        'error'
      );
      return;
    }

    if (!this.nodes?.length && !this.config.collections?.length) {
      this.isMissingCollectionsOrNodes = true;
      this.logMessage(
        'Add at least one node list item or one variable collection',
        'error'
      );
      return;
    }

    this.valid = true;
    this.logMessage('FigmaDesignTokens successfully initialized.', 'success');
  }

  private logMessage(message: string, type?: Parameters<typeof logMessage>[1]) {
    logMessage(`[${this.appName}] ${message}`, type);
  }

  public async generate() {
    if (!this.valid) {
      if (this.isMissingCollectionsOrNodes) {
        await this.displayVariableCollections();
      }

      throw new Error(
        'Attempted to generate design tokens, but config is invalid. See above errors.'
      );
    }

    const tasks = [];

    if (this.config.collections?.length) {
      this.logMessage(
        'Starting to generate design tokens from variable collections..',
        'info'
      );
      tasks.push(this.generateTokensFromVariableCollection());
    }

    if (this.nodes?.length) {
      this.logMessage(
        'Starting to generate design tokens from nodes..',
        'info'
      );
      tasks.push(this.generateTokensFromNodes());
    }

    if (this.config.version === 1 && this.config.fetchStyles) {
      this.logMessage(
        'Starting to generate design tokens from file styles..',
        'info'
      );
      tasks.push(this.generateTokensFromStyles());
    }

    await Promise.all(tasks);
  }

  private async generateTokensFromStyles() {
    if (this.config.version !== 1 || !this.config.fetchStyles) return;
    const { textStylePattern, effectStylePattern, fillStylePattern } = this.config.fetchStyles;

    // Step 1: Get all style references from the file
    this.logMessage('Fetching all styles from file...', 'info');
    const allStyles = await fetchFigmaFileStyles(this.config.figmaFileId);
    const styleCount = Object.keys(allStyles).length;
    this.logMessage(`Found ${styleCount} styles in file`, 'info');

    // Filter styles by pattern
    const textNodeIds: string[] = [];
    const effectNodeIds: string[] = [];
    const fillNodeIds: string[] = [];

    for (const [nodeId, style] of Object.entries(allStyles)) {
      if (style.styleType === 'TEXT' && textStylePattern?.test(style.name)) {
        textNodeIds.push(nodeId);
      }
      if (style.styleType === 'EFFECT' && effectStylePattern?.test(style.name)) {
        effectNodeIds.push(nodeId);
      }
      if (style.styleType === 'FILL' && fillStylePattern?.test(style.name)) {
        fillNodeIds.push(nodeId);
      }
    }

    this.logMessage(`Matched: ${textNodeIds.length} text, ${effectNodeIds.length} effect, ${fillNodeIds.length} fill styles`, 'info');

    // Step 2: Fetch node properties
    const allNodeIds = [...textNodeIds, ...effectNodeIds, ...fillNodeIds];
    if (allNodeIds.length === 0) return;

    this.logMessage('Fetching style node properties...', 'info');
    const nodes = await fetchFigmaFileNodesBatched(allNodeIds, this.config.figmaFileId);

    // Helper: convert color to hex/rgba
    const toHex = (c: { r: number; g: number; b: number; a?: number }) => {
      const r = Math.round(c.r * 255);
      const g = Math.round(c.g * 255);
      const b = Math.round(c.b * 255);
      const a = c.a ?? 1;
      if (a < 0.99) return `rgba(${r}, ${g}, ${b}, ${parseFloat(a.toFixed(2))})`;
      return `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`;
    };

    // ── Process text styles ──
    interface TextEntry { name: string; fontSize: number; fontWeight: number; lineHeight: number; letterSpacing: number; }
    const textByGroup: Record<string, TextEntry[]> = {};

    for (const nodeId of textNodeIds) {
      const style = allStyles[nodeId];
      const node = nodes[nodeId];
      if (!node?.style) continue;

      const parts = style.name.split('/');
      const group = parts[0].toLowerCase();
      const entryName = parts.slice(1).join('/');
      const s = node.style;

      if (!textByGroup[group]) textByGroup[group] = [];
      textByGroup[group].push({
        name: entryName,
        fontSize: s.fontSize || 0,
        fontWeight: s.fontWeight || 400,
        lineHeight: Math.round(s.lineHeightPx || 0),
        letterSpacing: s.letterSpacing ? parseFloat(s.letterSpacing.toFixed(4)) : 0,
      });
    }

    // Generate typography file
    const seen = new Set<string>();
    const formatGroup = (entries: TextEntry[]) => {
      seen.clear();
      return entries
        .map((e) => {
          const key = `${e.name.replace(/\s+/g, '-').toLowerCase()}${e.fontWeight <= 300 ? '-light' : ''}`;
          if (seen.has(key)) return null;
          seen.add(key);
          return `  "${key}": entry(${e.fontSize}, ${e.lineHeight}, ${e.fontWeight}, ${e.letterSpacing}),`;
        })
        .filter(Boolean)
        .join('\n');
    };

    let typoContent = `/**\n * This file is autogenerated by "figma-design-tokens"!\n * Last updated: ${new Date().toLocaleString()}\n */\n\n`;
    typoContent += `export const fontFamily = { sans: ["Roboto", "sans-serif"] } as const;\n\n`;
    typoContent += `type FontEntry = [string, { lineHeight: string; letterSpacing: string; fontWeight: string }];\n\n`;
    typoContent += `function entry(size: number, lh: number, weight: number, ls: number): FontEntry {\n`;
    typoContent += `  return [\`\${size}px\`, { lineHeight: \`\${lh}px\`, letterSpacing: ls ? \`\${ls}em\` : "0", fontWeight: String(weight) }];\n}\n\n`;

    for (const [group, entries] of Object.entries(textByGroup)) {
      typoContent += `export const ${group} = {\n${formatGroup(entries)}\n} as const;\n\n`;
    }
    typoContent += `export const fontSize = ${Object.keys(textByGroup)[0] || 'desktop'};\n`;

    await createTokenFile(typoContent, 'styles-typography', '', this.config.distFolder, this.config.fileExportType, this.appName);

    // ── Process effect styles ──
    const effects: Record<string, string> = {};
    for (const nodeId of effectNodeIds) {
      const style = allStyles[nodeId];
      const node = nodes[nodeId];
      if (!node?.effects?.length) continue;

      const key = style.name.replace(/\//g, '-').replace(/\s+/g, '-').toLowerCase();
      const value = node.effects
        .filter((e: any) => e.visible !== false && (e.type === 'DROP_SHADOW' || e.type === 'INNER_SHADOW'))
        .map((e: any) => {
          const prefix = e.type === 'INNER_SHADOW' ? 'inset ' : '';
          return `${prefix}${e.offset?.x ?? 0}px ${e.offset?.y ?? 0}px ${e.radius ?? 0}px ${e.spread ?? 0}px ${toHex(e.color)}`;
        })
        .join(', ');

      if (value) effects[key] = value;
    }

    // ── Process fill/gradient styles ──
    const gradients: Record<string, string> = {};
    for (const nodeId of fillNodeIds) {
      const style = allStyles[nodeId];
      const node = nodes[nodeId];
      if (!node?.fills?.length) continue;

      for (const fill of node.fills) {
        if (fill.visible === false) continue;
        if (fill.type !== 'GRADIENT_RADIAL' && fill.type !== 'GRADIENT_LINEAR') continue;
        const stops = (fill.gradientStops || []).map((s: any) => `${toHex(s.color)} ${Math.round(s.position * 100)}%`).join(', ');
        const type = fill.type === 'GRADIENT_RADIAL' ? 'radial-gradient' : 'linear-gradient';
        const key = style.name.replace(/\//g, '-').replace(/\s+/g, '-').toLowerCase();
        gradients[key] = `${type}(${stops})`;
      }
    }

    // Generate effects file
    const effectEntries = Object.entries(effects).map(([k, v]) => `  "${k}": "${v}"`).join(',\n');
    const gradientEntries = Object.entries(gradients).map(([k, v]) => `  "${k}": "${v}"`).join(',\n');

    let effectsContent = `/**\n * This file is autogenerated by "figma-design-tokens"!\n * Last updated: ${new Date().toLocaleString()}\n */\n\n`;
    effectsContent += `export const boxShadow = {\n${effectEntries}\n} as const;\n\n`;
    effectsContent += `export const gradient = {\n${gradientEntries}\n} as const;\n`;

    await createTokenFile(effectsContent, 'styles-effects', '', this.config.distFolder, this.config.fileExportType, this.appName);

    this.logMessage(
      `Generated: ${Object.values(textByGroup).reduce((a, b) => a + b.length, 0)} text styles, ${Object.keys(effects).length} effects, ${Object.keys(gradients).length} gradients`,
      'success'
    );
  }

  private async generateTokensFromNodes() {
    const nodeList = this.nodes;

    this.logMessage(
      'Fetching data from Figma. Please wait while we retrieve the necessary information..',
      'info'
    );
    try {
      this.styles = await fetchFigmaStyles(this.config.figmaFileId);

      if (this.styles?.length === 0) {
        this.logMessage(
          `No styles found in Figma file. Are you sure, you have published your styles in Figma?\nGuide can be found here https://help.figma.com/hc/en-us/articles/360025508373-Publish-styles-and-components`,
          'warning'
        );
        return;
      }
      if (!nodeList?.length) {
        this.logMessage(
          `No nodes found in config. Are you sure, you have added nodes to the config?`,
          'warning'
        );
        return;
      }

      const nodeDocuments = await fetchFigmaFileNodes(
        nodeList.map((node) => node.nodeId),
        this.config.figmaFileId
      );
      this.logMessage('Starting to generate design tokens..', 'info');
      await Promise.all(
        nodeList.map(async (node) => {
          const nodeDocument = nodeDocuments.find(
            (nodeDoc) => nodeDoc.id === node.nodeId
          );
          if (!nodeDocument) {
            this.logMessage(
              `Could not find node with id ${node.nodeId} in Figma file`,
              'warning'
            );
            return;
          }
          switch (node.lookFor) {
            case 'typography':
              await this.generateTypographyTokens(nodeDocument);
              break;
            // add more node types here
            default:
              this.logMessage(`No match for ${node.lookFor}`, 'error');
          }
        })
      );
      this.logMessage('Finished generating design tokens! ', 'success');
    } catch (error) {
      this.logMessage(error as string, 'error');
    }
  }

  private async generateTokensFromVariableCollection() {
    try {
      const { variableCollections, variables } = await fetchFigmaVariables(
        this.config.figmaFileId
      );
      this.variableCollections = variableCollections;
      this.variables = variables;

      // For each specified variable collection attempt to generate design tokens
      const promises = (this.config.collections || []).map(
        async (collectionName) => {
          const collection = this.variableCollections[collectionName];

          if (!collection) {
            let possibleCollections = '';
            Object.keys(this.variableCollections).forEach((key) => {
              const col = this.variableCollections[key];
              possibleCollections += `${col.id} (${col.name})\n`;
            });

            this.logMessage(
              `Could not find variable collection with id ${collectionName}.\n\nPossible collections id's are:\n\n${possibleCollections}`,
              'warning'
            );
            return;
          }

          // Note: hiddenFromPublishing check removed to support remote/linked library collections
          if (collection.hiddenFromPublishing) {
            this.logMessage(
              `Collection "${collection.name}" is hidden from publishing — processing anyway`,
              'info'
            );
          }

          await this.generateTokensFromCollectionBasedOnVersion(collection);
        }
      );

      // Await all promises
      await Promise.all(promises);
    } catch (error) {
      this.logMessage(
        `Error generating tokens from variable collections: ${error instanceof Error ? error.message : String(error)}`,
        'error'
      );
    }
  }

  /** Get variable value based on id. If variable is an alias the referenced variable value will be returned */
  private getVariableValue(
    variableId: string
  ): string | number | boolean | Color | null {
    const variableValueOrAlias = this.variables[variableId];
    if (!variableValueOrAlias) {
      if (!this.config.ignoreMissingTokens) {
        this.logMessage(
          `Could not find variable with id ${variableId}. This might be because it references a variable in a collection that is hidden from publishing or not included in your config.`,
          'warning'
        );
      }
      return null;
    }

    const collection =
      this.variableCollections[variableValueOrAlias.variableCollectionId];

    if (!collection) {
      if (!this.config.ignoreMissingTokens) {
        this.logMessage(
          `Could not find collection for variable ${variableId}. The collection might be hidden from publishing.`,
          'warning'
        );
      }
      return null;
    }

    const variableValue =
      variableValueOrAlias.valuesByMode[collection.defaultModeId];

    if (isVariableAlias(variableValue)) {
      return this.getVariableValue(variableValue.id);
    }

    return variableValue as string | number | boolean | Color;
  }

  private async generateTokensFromCollectionBasedOnVersion(
    collection: IVariableCollection
  ) {
    switch (this.config.version) {
      case 2:
      case 1:
      default:
        return await this.generateTokensFromCollectionV1(collection);
    }
  }

  private async generateTokensFromCollectionV1(
    collection: IVariableCollection
  ) {
    const variablesArray = Object.values(this.variables);

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const groupedVariables = variablesArray?.reduce<any>((acc, variable) => {
      if (variable.variableCollectionId !== collection.id) return acc;

      const tailwindName = variable.name.replace(/\//g, '-');
      const variableValue = this.getVariableValue(variable.id);

      if (variableValue === null) {
        return acc;
      }

      const variableAsString = isColorValue(variableValue)
        ? convertRgbaToHex(variableValue)
        : variableValue.toString();

      const [group, ...keyNames] = tailwindName.split('-');

      if (!acc[group]) {
        acc[group] = {};
      }

      acc[group][keyNames.join('-')] = variableAsString;

      return acc;
    }, {});

    const textContent = `
      ${autogeneratedText}
      export const tokens = ${JSON.stringify(groupedVariables)}
    `;

    const content = await prettifyContent(textContent);

    await createTokenFile(
      content,
      `variables-${collection.name}`.replace(/\s/g, '-'),
      '',
      this.config.distFolder,
      this.config.fileExportType,
      this.appName
    );
  }

  private async displayVariableCollections() {
    try {
      const { variableCollections } = await fetchFigmaVariables(
        this.config.figmaFileId
      );
      const collectionNames = Object.values(variableCollections)
        .sort((a, b) => (a.name === b.name ? 0 : a.name > b.name ? 1 : -1))
        .sort((a, b) =>
          a.hiddenFromPublishing === b.hiddenFromPublishing
            ? 0
            : a.hiddenFromPublishing
              ? 1
              : -1
        );

      let collectionNamesString = chalk.blue(
        'Enabled collections (likely one or more of these you need to use):\n'
      );
      collectionNamesString +=
        collectionNames
          .filter((collection) => !collection.hiddenFromPublishing)
          .map((collection) =>
            chalk.white(
              `- ${collection.name} [${collection.modes.map((mode) => mode.name).join('+ ')}] - ${chalk.bgGrey(collection.id)}`
            )
          )
          .join('\n') + '\n';

      collectionNamesString += chalk.blue(
        'These collections are likely not to be used, but shown for full transparency:\n'
      );
      collectionNamesString +=
        collectionNames
          .filter((collection) => collection.hiddenFromPublishing)
          .map((collection) =>
            chalk.red(
              `- ${collection.name} [${collection.modes.map((mode) => mode.name).join(', ')}] - ${collection.id}`
            )
          )
          .join('\n') + '\n';

      this.logMessage(
        chalk.yellow(
          'No variable collections found in config. Here are the available collections in the Figma file:\n'
        ) + collectionNamesString,
        'log'
      );
    } catch (error) {
      this.logMessage(
        `Error trying to get variable collections: "${'TODO'}": ${error}`,
        'warning'
      );
    }
  }

  private async generateTypographyTokens(nodeDocument: FigmaNode) {
    try {
      const typographyStyles: ITypographyStyles[] =
        this.styles
          ?.filter((style) => style.style_type === 'TEXT')
          .map((style) => {
            const typographyValue = findTypographyTokens(
              style.node_id,
              nodeDocument
            );

            const cssStyle = typographyValue
              ? this.formatTypography(typographyValue)
              : undefined;

            const typographyItem: ITypographyStyles = {
              name: style.name,
              description: style.description || '',
              nodeId: style.node_id,
              cssStyle,
            };

            return typographyItem;
          })
          .filter((item) => item.name)
          .filter((item) =>
            this.config.ignoreMissingTokens ? item.cssStyle : true
          )
          .sort((a, b) => (a.name > b.name ? 1 : -1)) || [];

      if (typographyStyles.length === 0) {
        throw new Error(
          `No typography styles found in Figma file. ${nodeDocument.name}`
        );
      }
      const tokens = await formatTypographyTokensAsTailwind(
        typographyStyles,
        'object'
      );

      await createTokenFile(
        tokens,
        'typography',
        nodeDocument.id,
        this.config.distFolder,
        this.config.fileExportType,
        this.appName
      );
    } catch (error) {
      this.logMessage(
        `Error trying to get typography styles for node: "${nodeDocument.id}": ${error}`,
        'warning'
      );
    }
  }

  private formatTypography = (typography: TypeStyle) => {
    const customSizeFunction = (this.config as IConfigV1)
      ?.customFluidFontSizeFunction;
    const useSizeFunction = !!(this.config.version === 1 && customSizeFunction);

    return {
      fontSize: useSizeFunction
        ? customSizeFunction(typography?.fontSize)
        : `${typography?.fontSize}px`,
      fontFamily: typography?.fontFamily,
      fontWeight: typography?.fontWeight,
      letterSpacing: typography?.letterSpacing
        ? `${typography.letterSpacing / typography.fontSize}em`
        : 'normal',
      lineHeight: `${
        Math.round(typography.lineHeightPx) / typography.fontSize
      }`,
      textTransform: typography?.textCase === 'UPPER' ? 'uppercase' : 'none',
    };
  };
}
