/**
 * This file is autogenerated by "figma-design-tokens"!
 * Last updated: 29.3.2026, 14.40.57
 * If you edit this file, it will be overwritten, next time you run the command.
 */

export const tokens = {
  Text: {
    'Brand Color': '#004a62ff',
    'Secondary Text Color': '#667085ff',
    'Tertiary Text Color': '#98a2b3ff',
  },
  Border: { 'Border Secondary': '#f2f4f7ff', 'Border Tertiary': '#d0d5ddff' },
  Logo: { 'Logo Icon Background': '#004a62ff' },
  'Sidebar navigation': {
    'Nav Item-Nav Active Text': '#004a62ff',
    'Nav Item-Icon': '#667085ff',
  },
  Alerts: { 'Success-Icon': '#12b76aff', 'Info-Border': '#0ba5ecff' },
  Card: { 'Secondary Background': '#f2f4f7ff' },
  Status: {
    'Gray-Light Background': '#f2f4f7ff',
    'Gray-Solid Background': '#98a2b3ff',
    'Primary-Solid Background': '#004a62ff',
  },
  Input: { 'Placeholder text color': '#98a2b3ff' },
  Tab: { Background: '#f2f4f7ff' },
  Button: { 'Stroke-Stroke': '#d0d5ddff' },
  Calendar: { 'Calendar Selected Date-Primary Badge': '#004a62ff' },
  'File Manager': {
    'Icon bg 1': '#12b76a14',
    'Icon bg 2': '#ee46bc14',
    'Icon bg 3': '#0ba5ec14',
    'Icon bg 4': '#fb651414',
    'Icon bg 5': '#f7900914',
    'Icon bg 6': '#7a5af814',
  },
};
